### ISSUE TITLE
Shall we just ignore the timezone of AMF0

### ISSUE THREAD

**Issue by asypost** [sile/amf#10]
Shall we just ignore the timezone of AMF0 as it's reserved?

**Comment by sile** [comment]
This crate raises an error during decoding when a non-zero timezone is used ([code](https://github.com/sile/amf/blob/01a13f279eb37196b574dae28a168363d9e0c97c/src/amf0/decode.rs#L127)).

**Comment by asypost** [comment]
I know that,I have read the source code.Consider this situation: If the parser is parsing a nonzero time zone date value of a ECMA Array key, and then I catch the error and continue the parsing process ,what will happen next? In my case I encountered an error.

发自我的iPhone

**Comment by sile** [comment]
Sorry, I misunderstood your intention.

> what will happen next? In my case I encountered an error.

Yes. With the current implementation, resulting in an error is the expected behavior.

I'm willing to change the code to accept non-zero timezone fields.
However, IMO, it feels better to add a new field named `timezone` to the [`amf::amf0::Value::Date`](https://docs.rs/amf/0.3.1/amf/amf0/enum.Value.html) enum instead of just ignoring timezone values.

What do you think of that?

**Comment by asypost** [comment]
Totally agree!

发自我的iPhone

**Comment by sile** [comment]
Added the field in #11 and released v0.4.0.
